[server]

default_n = 20

cache_expire = "30s"

[recommend]

cache_size = 100
cache_expire = "48h"

[recommend.data_source]

positive_feedback_types = ["like", "favorite", "repost", "comment"]

read_feedback_types = ["read"]

positive_feedback_ttl = 7

item_ttl = 7

[recommed.popular]

popular_window = "360h"

[recommend.offline]

enable_latest_recommend = true

enable_popular_recommend = true

enable_user_based_recommend = true

enable_item_based_recommend = true

enable_collaborative_recommend = true

enable_click_through_prediction = true

explore_recommend = { popular = 0.1, latest = 0.2 }

[recomend.online]

fallback_recommend = ["item_based", "user_based", "latest"]

num_feedback_fallback_item_based = 20